openapi: 3.1.0
info:
  title: GPT Dev Log API - Full Endpoint Access
  version: "1.4"
servers:
  - url: https://gpt-dev-log-api.onrender.com
paths:
  /sheet/write_row:
    post:
      operationId: writeSheetRow
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - sheet_name
              properties:
                # Core
                sheet_name:
                  type: string

                # Journal / Macro Logs
                unified_log_id:
                  type: string
                origin_sheet:
                  type: string
                title:
                  type: string
                summary:
                  type: string
                outcome:
                  type: string
                linked_sheets:
                  type: string
                linked_log_ids:
                  type: string
                author:
                  type: string
                notes:
                  type: string

                # Integration / GPT Logs
                timestamp:
                  type: string
                message:
                  type: string
                gpt:
                  type: string
                context:
                  type: string
                event:
                  type: string
                action:
                  type: string
                result:
                  type: string
                details:
                  type: string

                # Event Triggers
                trigger_phrase:
                  type: string
                detected_by:
                  type: string
                target_action:
                  type: string
                tags:
                  type: string

                # Field Definitions
                field_name:
                  type: string
                type:
                  type: string
                required:
                  type: string
                description:
                  type: string
                default:
                  type: string
                example:
                  type: string

                # GPT Verification / Validation
                test_case:
                  type: string
                scenario:
                  type: string
                expected_behavior:
                  type: string
                actual_behavior:
                  type: string
                expected:
                  type: string
                validated_output:
                  type: string
                validator:
                  type: string
                status:
                  type: string
                comments:
                  type: string

                # Schema Change Log
                sheet_affected:
                  type: string
                change_type:
                  type: string
                before:
                  type: string
                after:
                  type: string
                reason:
                  type: string

                # Prototype Feedback
                test_context:
                  type: string
                observation:
                  type: string
                gpt_version:
                  type: string

                # Model Comparison
                test_id:
                  type: string
                prompt:
                  type: string
                response_summary:
                  type: string
                score:
                  type: string
                reviewer_notes:
                  type: string

                # Sandbox
                col_a:
                  type: string
                col_b:
                  type: string
                col_c:
                  type: string
                col_d:
                  type: string
                col_e:
                  type: string
                col_f:
                  type: string
                col_g:
                  type: string
                col_h:
                  type: string
                col_i:
                  type: string
                test_marker:
                  type: string
                log_id:
                  type: string
                status:
                  type: string
                notes:
                  type: string
                timestamp:
                  type: string
                summary:
                  type: string
                action:
                  type: string

                # Feature Log
                feature:
                  type: string
                date_added:
                  type: string
                related_log_id:
                  type: string

                # Task Log
                task:
                  type: string
                assigned_to:
                  type: string
                due_date:
                  type: string
                priority:
                  type: string
                linked_log_id:
                  type: string

                # Issue Queue
                issue_id:
                  type: string
                description:
                  type: string
                severity:
                  type: string
                date_reported:
                  type: string
                logged_by:
                  type: string
                resolution_log_id:
                  type: string

                # Dashboard
                log_id:
                  type: string
                log_type:
                  type: string
                next_action:
                  type: string

                # Daily Summary
                date:
                  type: string
                gpt_notes:
                  type: string
                highlights:
                  type: string
                next_actions:
                  type: string
                linked_logs:
                  type: string

                # Metrics Tracker
                logs_created:
                  type: string
                errors_logged:
                  type: string
                tasks_completed:
                  type: string
                open_issues:
                  type: string
                comments:
                  type: string

                # Extra useful fields (future-proofing)
                category:
                  type: string
                owner:
                  type: string
                reviewer:
                  type: string
                version:
                  type: string
                environment:
                  type: string
                location:
                  type: string
                duration:
                  type: string
                outcome_detail:
                  type: string
      security:
        - BearerAuth: []
  /sheet/write_passthrough_log:
    post:
      operationId: writePassthroughLog
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                sheet_name:
                  type: string
                log_id:
                  type: string
                status:
                  type: string
                notes:
                  type: string
                timestamp:
                  type: string
                summary:
                  type: string
                action:
                  type: string
      security:
        - BearerAuth: []
  /sheet/get_item:
    post:
      operationId: getInventoryItemBySheet
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                sheet_name:
                  type: string
                item_name:
                  type: string
      security:
        - BearerAuth: []
  /sheet/get_headers:
    post:
      operationId: getSheetHeaders
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                sheet_name:
                  type: string
      security:
        - BearerAuth: []
  /sheet/get_all:
    post:
      operationId: getStructuredSheet
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                sheet_name:
                  type: string
      security:
        - BearerAuth: []
  /sheet/get_by_location:
    post:
      operationId: getByLocationBySheet
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                sheet_name:
                  type: string
                location_id:
                  type: string
      security:
        - BearerAuth: []
  /updateSheetHeaders:
    post:
      operationId: updateSheetHeaders
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                sheet_name:
                  type: string
                headers:
                  type: array
                  items:
                    type: string
      security:
        - BearerAuth: []
  /log:
    post:
      operationId: logEvent
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                timestamp:
                  type: string
                source:
                  type: string
                severity:
                  type: string
                message:
                  type: string
                details:
                  type: string
      security:
        - BearerAuth: []
  /habits/update:
    post:
      operationId: updateHabit
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                date:
                  type: string
                habit:
                  type: string
                status:
                  type: string
                notes:
                  type: string
      security:
        - BearerAuth: []
  /goals/update:
    post:
      operationId: updateGoal
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                goal_name:
                  type: string
                target_date:
                  type: string
                progress:
                  type: string
                status:
                  type: string
                priority:
                  type: string
      security:
        - BearerAuth: []
  /mental_state/update:
    post:
      operationId: updateMentalState
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                date:
                  type: string
                mood:
                  type: string
                energy:
                  type: string
                notes:
                  type: string
      security:
        - BearerAuth: []
  /submitJournalV3:
    post:
      operationId: submitJournalEntry
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                sheet_name:
                  type: string
                entry_data:
                  type: object
                  additionalProperties: true
                write_key:
                  type: string
      security:
        - BearerAuth: []
  /sheet/create:
    post:
      operationId: createSheet
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - sheet_name
              properties:
                sheet_name:
                  type: string
                headers:
                  type: array
                  items:
                    type: string
      security:
        - BearerAuth: []
  /sheet/rename:
    post:
      operationId: renameSheet
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - old_name
                - new_name
              properties:
                old_name:
                  type: string
                new_name:
                  type: string
      security:
        - BearerAuth: []
  /sheet/delete:
    post:
      operationId: deleteSheet
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - sheet_name
              properties:
                sheet_name:
                  type: string
      security:
        - BearerAuth: []
  /sheet/list_all:
    get:
      operationId: listAllSheets
      responses:
        "200":
          description: A list of sheet names
      security:
        - BearerAuth: []
securitySchemes:
  BearerAuth:
    type: http
    scheme: bearer
