openapi: 3.1.0
info:
  title: GPT Dev Log API with Explicit Fields
  version: "1.1"
servers:
  - url: https://gpt-dev-log-api.onrender.com
paths:
  /sheet/write_passthrough_log:
    post:
      operationId: writePassthroughLog
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - sheet_name
              properties:
                sheet_name:
                  type: string
                Echo:
                  type: string
                Timestamp:
                  type: string
                JIT_Log_Test:
                  type: string
      security:
        - BearerAuth: []
securitySchemes:
  BearerAuth:
    type: http
    scheme: bearer