openapi: 3.1.0
info:
  title: Minimal API No Components
  version: "1.0"
servers:
  - url: https://gpt-dev-log-api.onrender.com
paths:
  /sheet/write_row:
    post:
      operationId: writeSheetRow
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - sheet_name
                - item
              properties:
                sheet_name:
                  type: string
                item:
                  type: object
                  additionalProperties: true
      security:
        - BearerAuth: []
securitySchemes:
  BearerAuth:
    type: http
    scheme: bearer
