openapi: 3.1.0
info:
  title: GPT Dev Log API - Full Endpoint Access
  version: "1.4"
servers:
  - url: https://gpt-dev-log-api.onrender.com
paths:
  /sheet/write_row:
    post:
      operationId: writeSheetRow
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - sheet_name
              properties:
                sheet_name:
                  type: string
                Log ID:
                  type: string
                Status:
                  type: string
                Notes:
                  type: string
                Timestamp:
                  type: string
                Summary:
                  type: string
                Action:
                  type: string
      security:
        - BearerAuth: []
  /sheet/write_passthrough_log:
    post:
      operationId: writePassthroughLog
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                sheet_name:
                  type: string
              patternProperties:
                ".*":
                  type: string
      security:
        - BearerAuth: []
  /sheet/get_item:
    post:
      operationId: getInventoryItemBySheet
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                sheet_name:
                  type: string
                item_name:
                  type: string
      security:
        - BearerAuth: []
  /sheet/get_headers:
    post:
      operationId: getSheetHeaders
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                sheet_name:
                  type: string
      security:
        - BearerAuth: []
  /sheet/get_all:
    post:
      operationId: getStructuredSheet
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                sheet_name:
                  type: string
      security:
        - BearerAuth: []
  /sheet/get_by_location:
    post:
      operationId: getByLocationBySheet
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                sheet_name:
                  type: string
                location_id:
                  type: string
      security:
        - BearerAuth: []
  /updateSheetHeaders:
    post:
      operationId: updateSheetHeaders
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                sheet_name:
                  type: string
                headers:
                  type: array
                  items:
                    type: string
      security:
        - BearerAuth: []
  /log:
    post:
      operationId: logEvent
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                item:
                  type: object
                  patternProperties:
                    ".*":
                      type: string
      security:
        - BearerAuth: []
  /habits/update:
    post:
      operationId: updateHabit
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                sheet_name:
                  type: string
                item:
                  type: object
                  additionalProperties: true
      security:
        - BearerAuth: []
  /goals/update:
    post:
      operationId: updateGoal
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                sheet_name:
                  type: string
                item:
                  type: object
                  additionalProperties: true
      security:
        - BearerAuth: []
  /mental_state/update:
    post:
      operationId: updateMentalState
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                sheet_name:
                  type: string
                item:
                  type: object
                  additionalProperties: true
      security:
        - BearerAuth: []
  /submitJournalV3:
    post:
      operationId: submitJournalEntry
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                sheet_name:
                  type: string
                entry_data:
                  type: object
                  additionalProperties: true
                write_key:
                  type: string
      security:
        - BearerAuth: []
  /sheet/create:
    post:
      operationId: createSheet
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - sheet_name
              properties:
                sheet_name:
                  type: string
                headers:
                  type: array
                  items:
                    type: string
      security:
        - BearerAuth: []
  /sheet/rename:
    post:
      operationId: renameSheet
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - old_name
                - new_name
              properties:
                old_name:
                  type: string
                new_name:
                  type: string
      security:
        - BearerAuth: []
  /sheet/delete:
    post:
      operationId: deleteSheet
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - sheet_name
              properties:
                sheet_name:
                  type: string
      security:
        - BearerAuth: []
  /sheet/list_all:
    get:
      operationId: listAllSheets
      responses:
        "200":
          description: A list of sheet names
      security:
        - BearerAuth: []
securitySchemes:
  BearerAuth:
    type: http
    scheme: bearer
