openapi: 3.1.0
info:
  title: GPT Dev Log API with Logging Endpoint
  version: "1.0"
servers:
  - url: https://gpt-dev-log-api.onrender.com
paths:
  /sheet/write_passthrough:
    post:
      operationId: writePassthrough
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - sheet_name
              properties:
                sheet_name:
                  type: string
              additionalProperties: true
      security:
        - BearerAuth: []
  /sheet/write_passthrough_log:
    post:
      operationId: writePassthroughLog
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - sheet_name
              properties:
                sheet_name:
                  type: string
              additionalProperties: true
      security:
        - BearerAuth: []
securitySchemes:
  BearerAuth:
    type: http
    scheme: bearer
