openapi: 3.1.0
info:
  title: GPT Dev Log API - Full Endpoint Access
  version: "1.4"
servers:
  - url: https://gpt-dev-log-api.onrender.com
paths:
  /sheet/write_row:
    post:
      operationId: writeSheetRow
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - sheet_name
              properties:
                # Core
                sheet_name:
                  type: string

                # Journal / Macro Logs
                Unified Log ID:
                  type: string
                Title:
                  type: string
                Summary:
                  type: string
                Outcome:
                  type: string
                Linked Sheets:
                  type: string
                Linked Log IDs:
                  type: string
                Author:
                  type: string
                Notes:
                  type: string

                # Integration / GPT Logs
                Timestamp:
                  type: string
                Message:
                  type: string
                GPT:
                  type: string
                Context:
                  type: string
                Event:
                  type: string
                Action:
                  type: string
                Result:
                  type: string
                Details:
                  type: string

                # Event Triggers
                Trigger Phrase:
                  type: string
                Detected By:
                  type: string
                Target Action:
                  type: string
                Tags:
                  type: string

                # Field Definitions
                Field Name:
                  type: string
                Type:
                  type: string
                Required:
                  type: string
                Description:
                  type: string
                Default:
                  type: string
                Example:
                  type: string

                # GPT Verification / Validation
                Test Case:
                  type: string
                Scenario:
                  type: string
                Expected Behavior:
                  type: string
                Actual Behavior:
                  type: string
                Expected:
                  type: string
                Validated Output:
                  type: string
                Validator:
                  type: string
                Status:
                  type: string
                Comments:
                  type: string

                # Schema Change Log
                Sheet Affected:
                  type: string
                Change Type:
                  type: string
                Before:
                  type: string
                After:
                  type: string
                Reason:
                  type: string

                # Prototype Feedback
                Test Context:
                  type: string
                Observation:
                  type: string
                GPT Version:
                  type: string

                # Model Comparison
                Test ID:
                  type: string
                Prompt:
                  type: string
                Response Summary:
                  type: string
                Score:
                  type: string
                Reviewer Notes:
                  type: string

                # Sandbox
                Col A:
                  type: string
                Col B:
                  type: string
                Col C:
                  type: string
                Col D:
                  type: string
                Col E:
                  type: string
                Col F:
                  type: string
                Col G:
                  type: string
                Col H:
                  type: string
                Col I:
                  type: string
                Test Marker:
                  type: string
                log_id:
                  type: string
                status:
                  type: string
                notes:
                  type: string
                timestamp:
                  type: string
                summary:
                  type: string
                action:
                  type: string

                # Feature Log
                Feature:
                  type: string
                Date Added:
                  type: string
                Related Log ID:
                  type: string

                # Task Log
                Task:
                  type: string
                Assigned To:
                  type: string
                Due Date:
                  type: string
                Priority:
                  type: string
                Linked Log ID:
                  type: string

                # Issue Queue
                Issue ID:
                  type: string
                Description:
                  type: string
                Severity:
                  type: string
                Date Reported:
                  type: string
                Logged By:
                  type: string
                Resolution Log ID:
                  type: string

                # Dashboard
                Log ID:
                  type: string
                Log Type:
                  type: string
                Next Action:
                  type: string

                # Daily Summary
                Date:
                  type: string
                GPT Notes:
                  type: string
                Highlights:
                  type: string
                Next Actions:
                  type: string
                Linked Logs:
                  type: string

                # Metrics Tracker
                Logs Created:
                  type: string
                Errors Logged:
                  type: string
                Tasks Completed:
                  type: string
                Open Issues:
                  type: string
                Comments:
                  type: string

                # System-style logs (from 4.5_Log_Index)
                source:
                  type: string
                severity:
                  type: string
                message:
                  type: string
                details:
                  type: string

                # 🔮 Extra useful fields (future-proofing)
                Category:
                  type: string
                Owner:
                  type: string
                Reviewer:
                  type: string
                Version:
                  type: string
                Environment:
                  type: string
                Location:
                  type: string
                Duration:
                  type: string
                Outcome Detail:
                  type: string
      security:
        - BearerAuth: []
  /sheet/write_passthrough_log:
    post:
      operationId: writePassthroughLog
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                sheet_name:
                  type: string
                log_id:
                  type: string
                status:
                  type: string
                notes:
                  type: string
                timestamp:
                  type: string
                summary:
                  type: string
                action:
                  type: string
      security:
        - BearerAuth: []
  /sheet/get_item:
    post:
      operationId: getInventoryItemBySheet
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                sheet_name:
                  type: string
                item_name:
                  type: string
      security:
        - BearerAuth: []
  /sheet/get_headers:
    post:
      operationId: getSheetHeaders
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                sheet_name:
                  type: string
      security:
        - BearerAuth: []
  /sheet/get_all:
    post:
      operationId: getStructuredSheet
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                sheet_name:
                  type: string
      security:
        - BearerAuth: []
  /sheet/get_by_location:
    post:
      operationId: getByLocationBySheet
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                sheet_name:
                  type: string
                location_id:
                  type: string
      security:
        - BearerAuth: []
  /updateSheetHeaders:
    post:
      operationId: updateSheetHeaders
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                sheet_name:
                  type: string
                headers:
                  type: array
                  items:
                    type: string
      security:
        - BearerAuth: []
  /log:
    post:
      operationId: logEvent
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                timestamp:
                  type: string
                source:
                  type: string
                severity:
                  type: string
                message:
                  type: string
                details:
                  type: string
      security:
        - BearerAuth: []
  /habits/update:
    post:
      operationId: updateHabit
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                date:
                  type: string
                habit:
                  type: string
                status:
                  type: string
                notes:
                  type: string
      security:
        - BearerAuth: []
  /goals/update:
    post:
      operationId: updateGoal
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                goal_name:
                  type: string
                target_date:
                  type: string
                progress:
                  type: string
                status:
                  type: string
                priority:
                  type: string
      security:
        - BearerAuth: []
  /mental_state/update:
    post:
      operationId: updateMentalState
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                date:
                  type: string
                mood:
                  type: string
                energy:
                  type: string
                notes:
                  type: string
      security:
        - BearerAuth: []
  /submitJournalV3:
    post:
      operationId: submitJournalEntry
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                sheet_name:
                  type: string
                entry_data:
                  type: object
                  additionalProperties: true
                write_key:
                  type: string
      security:
        - BearerAuth: []
  /sheet/create:
    post:
      operationId: createSheet
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - sheet_name
              properties:
                sheet_name:
                  type: string
                headers:
                  type: array
                  items:
                    type: string
      security:
        - BearerAuth: []
  /sheet/rename:
    post:
      operationId: renameSheet
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - old_name
                - new_name
              properties:
                old_name:
                  type: string
                new_name:
                  type: string
      security:
        - BearerAuth: []
  /sheet/delete:
    post:
      operationId: deleteSheet
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - sheet_name
              properties:
                sheet_name:
                  type: string
      security:
        - BearerAuth: []
  /sheet/list_all:
    get:
      operationId: listAllSheets
      responses:
        "200":
          description: A list of sheet names
      security:
        - BearerAuth: []
securitySchemes:
  BearerAuth:
    type: http
    scheme: bearer
