openapi: 3.1.0
info:
  title: GPT Development Log API
  description: Unified schema for GPT endpoint interaction with Google Sheets
  version: "1.0"
servers:
  - url: https://gpt-dev-log-api.onrender.com
paths:
  /sheet/write_row:
    post:
      operationId: writeSheetRow
      summary: Write a new row into a specified sheet
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - sheet_name
                - item
              properties:
                sheet_name:
                  type: string
                item:
                  type: object
      responses:
        "200":
          description: Row written successfully

  /sheet/get_item:
    post:
      operationId: getInventoryItemBySheet
      summary: Get a specific item from a sheet
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                sheet_name:
                  type: string
                item_name:
                  type: string
      responses:
        "200":
          description: Item retrieved successfully

  /sheet/get_headers:
    post:
      operationId: getSheetHeaders
      summary: Retrieve headers from a sheet
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                sheet_name:
                  type: string
      responses:
        "200":
          description: Headers retrieved

  /sheet/get_all:
    post:
      operationId: getStructuredSheet
      summary: Retrieve all data from a sheet
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                sheet_name:
                  type: string
      responses:
        "200":
          description: All data retrieved

  /sheet/get_by_location:
    post:
      operationId: getByLocationBySheet
      summary: Get all rows for a specific location ID
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                sheet_name:
                  type: string
                location_id:
                  type: string
      responses:
        "200":
          description: Rows for location retrieved

  /updateSheetHeaders:
    post:
      operationId: updateSheetHeaders
      summary: Update the headers of a sheet
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                sheet_name:
                  type: string
                headers:
                  type: array
                  items:
                    type: string
      responses:
        "200":
          description: Headers updated

  /log:
    post:
      operationId: logEvent
      summary: Log an event or system activity
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                sheet_name:
                  type: string
                item:
                  type: object
      responses:
        "200":
          description: Log entry created

  /habits/update:
    post:
      operationId: updateHabit
      summary: Update or insert a habit record
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                sheet_name:
                  type: string
                item:
                  type: object
      responses:
        "200":
          description: Habit entry recorded

  /goals/update:
    post:
      operationId: updateGoal
      summary: Update or insert a goal entry
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                sheet_name:
                  type: string
                item:
                  type: object
      responses:
        "200":
          description: Goal entry recorded

  /mental_state/update:
    post:
      operationId: updateMentalState
      summary: Update mental state log
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                sheet_name:
                  type: string
                item:
                  type: object
      responses:
        "200":
          description: Mental state entry recorded

  /submitJournalV3:
    post:
      operationId: submitJournalEntry
      summary: Submit a full journal entry
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                sheet_name:
                  type: string
                entry_data:
                  type: object
                write_key:
                  type: string
      responses:
        "200":
          description: Journal entry submitted

  /sheet/create:
    post:
      operationId: createSheet
      summary: Create a new sheet tab
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - sheet_name
              properties:
                sheet_name:
                  type: string
                headers:
                  type: array
                  items:
                    type: string
      responses:
        "200":
          description: Sheet created
        "400":
          description: Missing name or invalid input

  /sheet/rename:
    post:
      operationId: renameSheet
      summary: Rename an existing sheet tab
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - old_name
                - new_name
              properties:
                old_name:
                  type: string
                new_name:
                  type: string
      responses:
        "200":
          description: Sheet renamed
        "400":
          description: Error renaming sheet

  /sheet/delete:
    post:
      operationId: deleteSheet
      summary: Delete a sheet tab
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - sheet_name
              properties:
                sheet_name:
                  type: string
      responses:
        "200":
          description: Sheet deleted
        "400":
          description: Deletion error

security: []